import Link from "next/link";
import { PageShell } from "@/components/page-shell";
import { getMacroSnapshot, sparklinePoints } from "@/lib/macro-data";
import { getPublishedArticles, getPublishedAudits } from "@/lib/public-content";
import { buildMetadata, jsonLd } from "@/lib/seo";
import { getCanonicalSiteUrl } from "@/lib/site-url";
import styles from "./home.module.css";

export const metadata = buildMetadata({ title: "ForexMax — Market Intelligence & Financial Research", description: "Source-aware financial research, official macro observations, risk context and practical tools.", path: "/" });
export const revalidate = 900;

const displayTime = (value: string) => new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(new Date(value));

export default async function Home() {
  const [audits, articles, macro] = await Promise.all([getPublishedAudits(), getPublishedArticles(), getMacroSnapshot()]);
  const research = [...audits, ...articles].sort((a, b) => b.updatedAt.getTime() - a.updatedAt.getTime()).slice(0, 5);
  const yieldObservation = macro.observations.find((item) => item.id === "us-10y");
  const siteUrl = getCanonicalSiteUrl();
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "Organization", name: "ForexMax Research", url: siteUrl, description: "Independent financial research and educational analysis." }, { "@type": "WebSite", name: "ForexMax", url: siteUrl }] };

  return <PageShell><script type="application/ld+json" dangerouslySetInnerHTML={jsonLd(schema)} /><div className={styles.page}>
    <section className={`shell ${styles.topbar}`}><p><span>TOP MARKET BRIEF</span> Official macro observations, source-linked research and risk context.</p><p>RETRIEVED <strong>{displayTime(macro.retrievedAt)} UTC</strong></p></section>
    <section className={`shell ${styles.brief}`}><div className={styles.briefLead}><p className={styles.kicker}>FOREXMAX / INTELLIGENCE DESK</p><h1>The record comes <em>before</em> the reaction.</h1><p>ForexMax connects published research with current official macro observations. Facts, time stamps and sources remain visible; market calls are never generated from a headline or a single data point.</p><div className={styles.actions}><Link href="/macro" className="button button-primary">Open macro desk</Link><Link href="/sources" className="button button-quiet">Inspect sources</Link></div></div><aside className={styles.commandPanel}><div><span>OFFICIAL INPUTS</span><strong>{macro.observations.length}</strong><small>usable observations in this retrieval</small></div><div><span>RESEARCH RECORDS</span><strong>{research.length}</strong><small>latest published archive entries shown</small></div><div><span>PUBLICATION CONTROL</span><strong>Human review</strong><small>required for new market assessments</small></div></aside></section>
    <section className={`shell ${styles.macroStrip}`}><div className={styles.stripIntro}><p className={styles.kicker}>GLOBAL MARKET BRIEF</p><h2>Official observations on the desk.</h2><p>Reference periods are shown with each reading. They are not real-time prices, forecasts or investment signals.</p><Link href="/macro" className="text-link">Full macro intelligence →</Link></div><div className={styles.factList}>{macro.observations.map((item) => <article key={item.id}><p>{item.label}</p><strong>{item.compactValueLabel ?? item.valueLabel}</strong><span>{item.referencePeriod}</span><a href={item.sourceUrl} target="_blank" rel="noreferrer">{item.sourceName} ↗</a></article>)}</div></section>
    <section className={`shell ${styles.dashboard}`}><article className={styles.ratesPanel}><div><p className={styles.kicker}>BONDS / RATES</p><h2>10-year Treasury context</h2>{yieldObservation ? <><strong>{yieldObservation.valueLabel}</strong><span>{yieldObservation.referencePeriod}</span></> : <p className={styles.panelNote}>The official daily series was not returned in this request.</p>}</div>{yieldObservation ? <div className={styles.sparkWrap}><svg viewBox="0 0 260 70" role="img" aria-label="Recent FRED DGS10 observations"><polyline points={sparklinePoints(macro.tenYearSeries)} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke" /></svg><p>Recent published FRED observations only.</p></div> : null}</article><article className={styles.riskPanel}><p className={styles.kicker}>RISK PROTOCOL</p><h2>What the desk will not do.</h2><ul><li>Turn one release into a market prediction.</li><li>Hide a source or its reference period.</li><li>Publish a new assessment without review.</li></ul><Link href="/methodology" className="text-link">Read methodology →</Link></article></section>
    <section className={`shell ${styles.researchGrid}`}><div className={styles.researchLead}><p className={styles.kicker}>LATEST RESEARCH</p><h2>Published records, not a content mill.</h2><p>The research archive remains separate from the incoming evidence workflow. New material must preserve source and review history before it can be published.</p><Link href="/articles" className="text-link">Research archive →</Link></div><div className={styles.researchList}>{research.map((item, index) => <article key={`${item.kind}-${item.slug}`}><span>0{index + 1}</span><div><p>{item.kind} / updated {new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(item.updatedAt)}</p><h3><Link href={item.route}>{item.title}</Link></h3><p>{item.description}</p></div></article>)}</div></section>
    <section className={`shell ${styles.sourceRail}`}><div><p className={styles.kicker}>SOURCE INTELLIGENCE</p><h2>Evidence starts with the publisher.</h2></div><div className={styles.sourceNotes}><article><span>01</span><h3>Official macro readings</h3><p>BLS and FRED observations are read from their official endpoints and displayed with a source link.</p></article><article><span>02</span><h3>Research evidence</h3><p>The next source-pipeline stage stores retrieval, verification, evidence and reviewer history in a safe Preview database.</p></article><article><span>03</span><h3>Assessment boundary</h3><p>Directional assessments remain unavailable until documented, measurable inputs and methodology exist.</p></article></div><Link href="/sources" className="text-link">Source registry →</Link></section>
    {macro.failures.length ? <aside className={`shell ${styles.sourceStatus}`}><strong>Source status</strong><span>{macro.failures.length} official input{macro.failures.length === 1 ? "" : "s"} could not be read in this request. No replacement value is shown.</span></aside> : null}
  </div></PageShell>;
}
