import Link from "next/link";
import { PageShell } from "@/components/page-shell";
import { economicEventContracts } from "@/lib/economic-events";
import { getMacroSnapshot, sparklinePoints } from "@/lib/macro-data";
import { marketDriverFrameworks } from "@/lib/market-drivers";
import { getMarketTapeSnapshot, marketTapeGroups } from "@/lib/market-tape";
import { getPublishedArticles, getPublishedAudits } from "@/lib/public-content";
import { buildMetadata, jsonLd } from "@/lib/seo";
import { getCanonicalSiteUrl } from "@/lib/site-url";
import styles from "./home.module.css";

export const metadata = buildMetadata({ title: "ForexMax — Market Intelligence & Financial Research", description: "Source-aware financial research, official macro observations, risk context and practical tools.", path: "/" });
export const revalidate = 900;

const displayTime = (value: string) => new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(new Date(value));

export default async function Home() {
  const [audits, articles, macro, tape] = await Promise.all([getPublishedAudits(), getPublishedArticles(), getMacroSnapshot(), getMarketTapeSnapshot()]);
  const research = [...audits, ...articles].sort((a, b) => b.updatedAt.getTime() - a.updatedAt.getTime()).slice(0, 5);
  const yieldObservation = macro.observations.find((item) => item.id === "us-10y");
  const marketBriefItems = tape.items.filter((item) => ["us-10y", "us-10y-real", "broad-usd", "wti", "vix"].includes(item.id));
  const siteUrl = getCanonicalSiteUrl();
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "Organization", name: "ForexMax Research", url: siteUrl, description: "Independent financial research and educational analysis." }, { "@type": "WebSite", name: "ForexMax", url: siteUrl }] };

  return <PageShell><script type="application/ld+json" dangerouslySetInnerHTML={jsonLd(schema)} /><div className={styles.page}>
    <section className={`shell ${styles.topbar}`}><p><span>TOP MARKET BRIEF</span> Official macro observations, published cross-asset records and source-linked research.</p><p>RETRIEVED <strong>{displayTime(tape.retrievedAt)} UTC</strong></p></section>
    <section className={`shell ${styles.brief}`}><div className={styles.briefLead}><p className={styles.kicker}>FOREXMAX / INTELLIGENCE DESK</p><h1>The record comes <em>before</em> the reaction.</h1><p>ForexMax brings published rates, dollar, energy, equity and risk observations into one evidence-first desk. Every value retains its publisher and observation date; no market call is generated from a headline or a single data point.</p><div className={styles.actions}><Link href="/macro" className="button button-primary">Open macro desk</Link><Link href="/markets" className="button button-quiet">Explore coverage</Link></div></div><aside className={styles.commandPanel}><div><span>PUBLISHED OBSERVATIONS</span><strong>{tape.items.length + macro.observations.length}</strong><small>cross-asset and macro records in this retrieval</small></div><div><span>RESEARCH RECORDS</span><strong>{research.length}</strong><small>latest published archive entries shown</small></div><div><span>PUBLICATION CONTROL</span><strong>Human review</strong><small>required before a market assessment can be published</small></div></aside></section>
    <section className={`shell ${styles.marketBrief}`}><div className={styles.marketBriefHeading}><div><p className={styles.kicker}>MARKET BRIEF</p><h2>What changed on the published record.</h2></div><p>The changes below compare the latest two valid observations for each named FRED series. They are not an explanation, forecast, trade signal or measure of market impact.</p></div><div className={styles.briefRows}>{marketBriefItems.map((item) => <article key={item.id}><div><span>{item.label}</span><strong>{item.valueLabel}</strong></div><div><b>{item.changeLabel}</b><small>vs. {item.previous.date}</small></div><div><time dateTime={item.latest.date}>{item.latest.date}</time><a href={item.sourceUrl} target="_blank" rel="noreferrer">{item.sourceName} ↗</a></div></article>)}</div><div className={styles.briefFooter}><p><strong>Why it matters:</strong> the desk keeps rates, dollar, energy, equity and risk observations adjacent so readers can inspect the record before drawing a cross-market conclusion.</p><Link href="/sources" className="text-link">Inspect source methodology →</Link></div></section>
    <section className={`shell ${styles.marketTape}`}><div className={styles.tapeHeading}><div><p className={styles.kicker}>GLOBAL MARKET CONTEXT</p><h2>A compact tape, not a terminal.</h2></div><p>Each line is a dated FRED observation from a named series. Non-business-day gaps and publisher update timing remain visible in the source record.</p></div>{marketTapeGroups.map((group) => { const items = tape.items.filter((item) => item.group === group.id); return items.length ? <section className={styles.tapeGroup} key={group.id}><header><p>{group.label}</p><span>{group.description}</span></header><div>{items.map((item) => <article key={item.id}><span>{item.label}</span><strong>{item.valueLabel}</strong><b>{item.changeLabel}</b><time dateTime={item.latest.date}>{item.latest.date}</time><a href={item.sourceUrl} target="_blank" rel="noreferrer">Source ↗</a></article>)}</div></section> : null; })}</section>
    <section className={`shell ${styles.macroStrip}`}><div className={styles.stripIntro}><p className={styles.kicker}>GLOBAL MARKET BRIEF</p><h2>Official observations on the desk.</h2><p>Reference periods are shown with each reading. They are not real-time prices, forecasts or investment signals.</p><Link href="/macro" className="text-link">Full macro intelligence →</Link></div><div className={styles.factList}>{macro.observations.map((item) => <article key={item.id}><p>{item.label}</p><strong>{item.compactValueLabel ?? item.valueLabel}</strong><span>{item.referencePeriod}</span><a href={item.sourceUrl} target="_blank" rel="noreferrer">{item.sourceName} ↗</a></article>)}</div></section>
    <section className={`shell ${styles.dashboard}`}><article className={styles.ratesPanel}><div><p className={styles.kicker}>BONDS / RATES</p><h2>10-year Treasury context</h2>{yieldObservation ? <><strong>{yieldObservation.valueLabel}</strong><span>{yieldObservation.referencePeriod}</span></> : <p className={styles.panelNote}>The official daily series was not returned in this request.</p>}</div>{yieldObservation ? <div className={styles.sparkWrap}><svg viewBox="0 0 260 70" role="img" aria-label="Recent FRED DGS10 observations"><polyline points={sparklinePoints(macro.tenYearSeries)} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke" /></svg><p>Recent published FRED observations only.</p></div> : null}</article><article className={styles.riskPanel}><p className={styles.kicker}>WHAT TO MONITOR</p><h2>Official release watch.</h2><ul>{economicEventContracts.map((event) => <li key={event.id}><a href={event.sourceUrl} target="_blank" rel="noreferrer">{event.event} ↗</a><small>{event.institution}</small></li>)}</ul><p className={styles.panelNote}>Release dates, consensus and reactions are intentionally omitted until an approved official event contract supplies them.</p></article></section>
    <section className={`shell ${styles.driverDesk}`}><div className={styles.driverHeading}><div><p className={styles.kicker}>RESEARCH MODEL</p><h2>Drivers need evidence, not adjectives.</h2></div><p>These are evidence maps for future asset research, not bullish or bearish assessments. Each route states what must be documented before a claim can be published.</p></div><div className={styles.driverGrid}>{marketDriverFrameworks.map((driver) => <article key={`${driver.asset}-${driver.driver}`}><p>{driver.label}</p><h3>{driver.driver}</h3><span>{driver.sourceContracts.join(" · ")}</span><small>{driver.requiredEvidence}</small></article>)}</div></section>
    <section className={`shell ${styles.researchGrid}`}><div className={styles.researchLead}><p className={styles.kicker}>LATEST RESEARCH</p><h2>Published records, not a content mill.</h2><p>The research archive remains separate from the incoming evidence workflow. New material must preserve source and review history before it can be published.</p><Link href="/articles" className="text-link">Research archive →</Link></div><div className={styles.researchList}>{research.map((item, index) => <article key={`${item.kind}-${item.slug}`}><span>0{index + 1}</span><div><p>{item.kind} / updated {new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(item.updatedAt)}</p><h3><Link href={item.route}>{item.title}</Link></h3><p>{item.description}</p></div></article>)}</div></section>
    <section className={`shell ${styles.sourceRail}`}><div><p className={styles.kicker}>SOURCE INTELLIGENCE</p><h2>Evidence starts with the publisher.</h2></div><div className={styles.sourceNotes}><article><span>01</span><h3>Official macro readings</h3><p>BLS and FRED observations are read from their official endpoints and displayed with a source link.</p></article><article><span>02</span><h3>Research evidence</h3><p>The next source-pipeline stage stores retrieval, verification, evidence and reviewer history in a safe Preview database.</p></article><article><span>03</span><h3>Assessment boundary</h3><p>Directional assessments remain unavailable until documented, measurable inputs and methodology exist.</p></article></div><Link href="/sources" className="text-link">Source registry →</Link></section>
    {macro.failures.length || tape.failures.length ? <aside className={`shell ${styles.sourceStatus}`}><strong>Source status</strong><span>{macro.failures.length + tape.failures.length} official input{macro.failures.length + tape.failures.length === 1 ? "" : "s"} could not be read in this request. No replacement value is shown.</span></aside> : null}
  </div></PageShell>;
}
