"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireDatabase, requireEditor } from "@/lib/admin";
import { propFirmInputSchema } from "@/lib/validation";

function nullable(value: FormDataEntryValue | null) { const string = String(value ?? "").trim(); return string || null; }
function payload(formData: FormData) { const input = propFirmInputSchema.parse({ name: formData.get("name"), slug: formData.get("slug"), country: nullable(formData.get("country")), challengeFee: nullable(formData.get("challengeFee")), profitTarget: nullable(formData.get("profitTarget")), profitSplit: nullable(formData.get("profitSplit")), dailyDrawdown: nullable(formData.get("dailyDrawdown")), maximumDrawdown: nullable(formData.get("maximumDrawdown")), payout: nullable(formData.get("payout")), newsTrading: nullable(formData.get("newsTrading")), weekendHolding: nullable(formData.get("weekendHolding")), expertAdvisor: nullable(formData.get("expertAdvisor")), consistency: nullable(formData.get("consistency")), scaling: nullable(formData.get("scaling")), platform: nullable(formData.get("platform")), evaluationType: nullable(formData.get("evaluationType")), assessment: nullable(formData.get("assessment")), lastReviewedAt: nullable(formData.get("lastReviewedAt")) }); const sourceName = nullable(formData.get("sourceName")); const sourceUrl = nullable(formData.get("sourceUrl")); const sourceType = nullable(formData.get("sourceType")) ?? "WEB"; if (!sourceName || !sourceUrl || !input.lastReviewedAt) throw new Error("PROP_FIRM_REQUIRES_SOURCE_AND_REVIEW_DATE"); return { input, sourceName, sourceUrl, sourceType }; }
function sourceRelation(data: ReturnType<typeof payload>) { return { create: { source: { connectOrCreate: { where: { url: data.sourceUrl }, create: { name: data.sourceName, url: data.sourceUrl, sourceType: data.sourceType, accessedAt: data.input.lastReviewedAt } } } } }; }
export async function createPropFirmAction(formData: FormData) { await requireEditor(); const db = requireDatabase(); const data = payload(formData); const firm = await db.propFirm.create({ data: { ...data.input, sources: sourceRelation(data) } }); revalidatePath("/prop-firm-comparison"); revalidatePath("/admin/prop-firms"); redirect(`/admin/prop-firms/${firm.id}`); }
export async function updatePropFirmAction(id: string, formData: FormData) { await requireEditor(); const db = requireDatabase(); const data = payload(formData); await db.propFirm.update({ where: { id }, data: { ...data.input, sources: { deleteMany: {}, ...sourceRelation(data) } } }); revalidatePath("/prop-firm-comparison"); revalidatePath("/admin/prop-firms"); revalidatePath(`/admin/prop-firms/${id}`); }
export async function deletePropFirmAction(id: string) { await requireEditor(); const db = requireDatabase(); await db.propFirm.delete({ where: { id } }); revalidatePath("/prop-firm-comparison"); revalidatePath("/admin/prop-firms"); redirect("/admin/prop-firms"); }
