"use client";

import Link from "next/link";
import { useState } from "react";

type SearchResult = { type: string; title: string; href: string; description: string };
export function SearchExperience() {
  const [query, setQuery] = useState(""); const [type, setType] = useState("all"); const [category, setCategory] = useState(""); const [page, setPage] = useState(1); const [hasMore, setHasMore] = useState(false); const [results, setResults] = useState<SearchResult[]>([]); const [message, setMessage] = useState("Enter at least two characters to search published research."); const [busy, setBusy] = useState(false);
  async function submit(nextPage = 1) { if (query.trim().length < 2) { setMessage("Enter at least two characters to search."); setResults([]); return; } setBusy(true); const search = new URLSearchParams({ q: query, type, page: String(nextPage), limit: "12" }); if (category.trim()) search.set("category", category.trim()); const response = await fetch(`/api/search?${search}`); const body = await response.json().catch(() => ({})); if (!response.ok) { setResults([]); setMessage(body.error ?? "Search could not be completed."); setBusy(false); return; } setPage(body.page); setHasMore(Boolean(body.hasMore)); setResults(body.results as SearchResult[]); setMessage(`${body.results.length} results found on page ${body.page}.`); setBusy(false); }
  return <section className="search-panel"><form className="search-controls" onSubmit={(event) => { event.preventDefault(); void submit(); }}><label>Search research<input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search articles, audits and firms" /></label><label>Type<select value={type} onChange={(event) => setType(event.target.value)}><option value="all">All content</option><option value="article">Articles</option><option value="audit">Audits</option><option value="prop-firm">Prop firms</option></select></label><label>Article category (optional)<input value={category} onChange={(event) => setCategory(event.target.value)} placeholder="e.g. macro" /></label><button className="button button-primary" disabled={busy}>{busy ? "Searching…" : "Search"}</button></form><p className="muted" role="status">{message} Category is an article-only filter. Search pages are noindex; results are a site utility, not a destination for search engines.</p><div className="search-results">{results.map((record) => <article key={`${record.type}-${record.href}-${record.title}`}><p className="eyebrow">{record.type}</p><h2><Link href={record.href}>{record.title}</Link></h2><p>{record.description}</p></article>)}</div>{results.length > 0 && <nav className="search-pagination" aria-label="Search pages"><button className="button" type="button" disabled={busy || page === 1} onClick={() => void submit(page - 1)}>Previous</button><span>Page {page}</span><button className="button" type="button" disabled={busy || !hasMore} onClick={() => void submit(page + 1)}>Next</button></nav>}</section>;
}
