create schema if not exists private;
create or replace function private.set_updated_at() returns trigger language plpgsql set search_path = public, private as $$ begin new."updatedAt" = now(); return new; end; $$;
create or replace function private.handle_new_user() returns trigger language plpgsql security definer set search_path = public, private as $$ begin insert into public.profiles (id, email, name) values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'full_name', new.email)) on conflict (id) do nothing; return new; end; $$;
create or replace function private.is_editor() returns boolean language sql stable security definer set search_path = public, private as $$ select exists (select 1 from public.profiles where id = auth.uid() and role in ('ADMIN', 'EDITOR')); $$;
create or replace function private.is_admin() returns boolean language sql stable security definer set search_path = public, private as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'ADMIN'); $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure private.handle_new_user();
alter policy "profiles_own_read" on public.profiles using (id = auth.uid() or private.is_editor());
alter policy "profiles_admin_manage" on public.profiles using (private.is_admin()) with check (private.is_admin());
alter policy "media_editor_manage" on public.media using (private.is_editor()) with check (private.is_editor());
alter policy "authors_editor_manage" on public.authors using (private.is_editor()) with check (private.is_editor());
alter policy "categories_editor_manage" on public.categories using (private.is_editor()) with check (private.is_editor());
alter policy "tags_editor_manage" on public.tags using (private.is_editor()) with check (private.is_editor());
alter policy "sources_editor_manage" on public.sources using (private.is_editor()) with check (private.is_editor());
alter policy "articles_editor_manage" on public.articles using (private.is_editor()) with check (private.is_editor());
alter policy "audits_editor_manage" on public.audits using (private.is_editor()) with check (private.is_editor());
alter policy "prop_firms_editor_manage" on public.prop_firms using (private.is_editor()) with check (private.is_editor());
alter policy "article_sources_editor_manage" on public.article_sources using (private.is_editor()) with check (private.is_editor());
alter policy "audit_sources_editor_manage" on public.audit_sources using (private.is_editor()) with check (private.is_editor());
alter policy "prop_firm_sources_editor_manage" on public.prop_firm_sources using (private.is_editor()) with check (private.is_editor());
alter policy "article_tags_editor_manage" on public."_ArticleTags" using (private.is_editor()) with check (private.is_editor());
alter policy "media_bucket_editor_insert" on storage.objects with check (bucket_id = 'media' and private.is_editor());
alter policy "media_bucket_editor_update" on storage.objects using (bucket_id = 'media' and private.is_editor()) with check (bucket_id = 'media' and private.is_editor());
alter policy "media_bucket_editor_delete" on storage.objects using (bucket_id = 'media' and private.is_editor());
drop function if exists public.handle_new_user();
drop function if exists public.is_editor();
drop function if exists public.is_admin();
