import type { Article, Author, Category, Media, ResearchSource, Tag } from "@/generated/prisma/client";

type ArticleWithSource = Article & { sources?: { source: ResearchSource }[]; tags?: Tag[] };
type ArticleOptions = { categories: Category[]; authors: Author[]; tags: Tag[]; media: Media[] };
export function ArticleForm({ action, article, options }: { action: (formData: FormData) => void | Promise<void>; article?: ArticleWithSource; options: ArticleOptions }) {
  const source = article?.sources?.[0]?.source;
  const selectedTags = new Set(article?.tags?.map((tag) => tag.id) ?? []);
  return <form action={action} className="admin-form"><div className="admin-form-grid"><label>Title<input required name="title" defaultValue={article?.title} maxLength={180} /></label><label>Slug<input required name="slug" pattern="[a-z0-9]+(-[a-z0-9]+)*" defaultValue={article?.slug} /></label><label>Category<select name="categoryId" defaultValue={article?.categoryId ?? ""}><option value="">Uncategorised</option>{options.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Author<select name="authorId" defaultValue={article?.authorId ?? ""}><option value="">No author selected</option>{options.authors.map((author) => <option key={author.id} value={author.id}>{author.name}</option>)}</select></label><label>Featured image<select name="featuredMediaId" defaultValue={article?.featuredMediaId ?? ""}><option value="">No featured image</option>{options.media.map((media) => <option key={media.id} value={media.id}>{media.filename}</option>)}</select></label><label>Tags<select name="tagIds" multiple defaultValue={[...selectedTags]}>{options.tags.map((tag) => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</select></label></div><label>Excerpt<textarea name="excerpt" rows={3} defaultValue={article?.excerpt ?? ""} maxLength={500} /></label><label>Content (Markdown)<textarea required name="contentMarkdown" rows={18} defaultValue={article?.contentMarkdown} /></label><div className="admin-form-grid"><label>Status<select name="status" defaultValue={article?.status ?? "DRAFT"}><option value="DRAFT">Draft</option><option value="REVIEW">Review</option><option value="PUBLISHED">Published</option><option value="UNPUBLISHED">Unpublished</option></select></label><label>Last reviewed<input name="lastReviewedAt" type="date" defaultValue={article?.lastReviewedAt ? article.lastReviewedAt.toISOString().slice(0, 10) : ""} /></label></div><fieldset><legend>Research source (required to publish new content)</legend><div className="admin-form-grid"><label>Source name<input name="sourceName" defaultValue={source?.name ?? ""} /></label><label>Source URL<input name="sourceUrl" type="url" defaultValue={source?.url ?? ""} /></label><label>Source type<input name="sourceType" defaultValue={source?.sourceType ?? "WEB"} /></label></div></fieldset><fieldset><legend>SEO</legend><label>SEO title<input name="seoTitle" defaultValue={article?.seoTitle ?? ""} maxLength={180} /></label><label>SEO description<textarea name="seoDescription" rows={2} defaultValue={article?.seoDescription ?? ""} maxLength={320} /></label><label>Canonical URL<input name="canonical" type="url" defaultValue={article?.canonical ?? ""} /></label><label>Open Graph image URL<input name="ogImage" type="url" defaultValue={article?.ogImage ?? ""} /></label></fieldset><button className="button button-primary" type="submit">Save article</button></form>;
}
